[package]
name = "zcash-android-wallet-sdk"
version = "0.0.8"
authors = [
    "Jack Grigg <jack@z.cash>",
    "Kevin Gorham <kevin.gorham@z.cash>",
]
description = "JNI backend for the Android wallet SDK"
publish = false
edition = "2018"

[dependencies]
android_logger = "0.9"
failure = "0.1"
hex = "0.4"
jni = { version = "0.17", default-features = false }
log = "0.4"
log-panics = "2.0.0"
zcash_client_backend = "0.5"
zcash_client_sqlite = "0.3"
zcash_primitives = "0.5"
zcash_proofs = "0.5"
zcash_note_encryption =  "0.0.0"

#### Temporary additions: ####################################
#base58 = "0.1.0"
#protobuf = "2"
#sha2 = "0.9"
#bs58 = { version = "0.3", features = ["check"] }

#ripemd160 = "0.9"
hdwallet = "0.3.0"
secp256k1 = "0.19"
funty = "=1.2.0"
bitvec = "0.22"
##############################################################

# update-sapling-tree dependencies
bls12_381 = { version = "0.5", optional = true }
futures = { version = "0.3", optional = true }
grpc = { version = "0.8", optional = true }
grpc-protobuf = { version = "0.8", optional = true }
httpbis = { version = "0.9", optional = true }
tls-api = { version = "0.4", optional = true }
tls-api-rustls = { version = "0.4", optional = true }

[build-dependencies]
protobuf-codegen-pure = "2.14"

#[patch.crates-io]
#zcash_client_backend = { git = 'https://github.com/zcash/librustzcash.git', rev='04a2bd4ad86980e0c2862706bd402b85b9dd1965' }
#zcash_client_sqlite = { git = 'https://github.com/zcash/librustzcash.git', rev='04a2bd4ad86980e0c2862706bd402b85b9dd1965' }
#zcash_primitives = { git = 'https://github.com/zcash/librustzcash.git', rev='04a2bd4ad86980e0c2862706bd402b85b9dd1965' }
#zcash_proofs = { git = 'https://github.com/zcash/librustzcash.git', rev='04a2bd4ad86980e0c2862706bd402b85b9dd1965' }

## Uncomment this to test librustzcash changes locally
#[patch.crates-io]
#zcash_client_backend = { path = '../../clones/librustzcash/zcash_client_backend' }
#zcash_client_sqlite = { path = '../../clones/librustzcash/zcash_client_sqlite' }
#zcash_primitives = { path = '../../clones/librustzcash/zcash_primitives' }
#zcash_proofs = { path = '../../clones/librustzcash/zcash_proofs' }

# Uncomment this to test someone else's librustzcash changes in a branch
[patch.crates-io]
zcash_client_backend = {git = "https://github.com/nuttycom/librustzcash", rev = "7d819b68a3da3ad568629bc6f51a63e39c2d7d6a" }
zcash_client_sqlite = {git = "https://github.com/nuttycom/librustzcash", rev = "7d819b68a3da3ad568629bc6f51a63e39c2d7d6a" }
zcash_primitives = {git = "https://github.com/nuttycom/librustzcash", rev = "7d819b68a3da3ad568629bc6f51a63e39c2d7d6a" }
zcash_proofs = {git = "https://github.com/nuttycom/librustzcash", rev = "7d819b68a3da3ad568629bc6f51a63e39c2d7d6a" }
zcash_note_encryption = { git = "https://github.com/zcash/librustzcash.git", rev = "13b023387bafdc7b5712c933dc0e16ee94b96a6a" }
# In development.
halo2 = { git = "https://github.com/zcash/halo2.git", rev = "27c4187673a9c6ade13fbdbd4f20955530c22d7f" }
orchard = { git = "https://github.com/zcash/orchard.git", rev = "d0baa18fc6105df4a7847de2b6dc50c5919b3123" }
incrementalmerkletree = { git = "https://github.com/zcash/incrementalmerkletree.git", rev = "b7bd6246122a6e9ace8edb51553fbf5228906cbb" }

# Unreleased
jubjub = { git = "https://github.com/zkcrypto/jubjub.git", rev = "96ab4162b83303378eae32a326b54d88b75bffc2" }

[features]
mainnet = ["zcash_client_sqlite/mainnet"]
testnet = []
updater = ["bls12_381", "futures", "grpc", "grpc-protobuf", "httpbis", "tls-api", "tls-api-rustls"]

[lib]
name = "zcashwalletsdk"
path = "src/main/rust/lib.rs"
crate-type = ["staticlib", "cdylib"]

[[bin]]
name = "update-sapling-tree"
path = "src/main/rust/bin/update_sapling_tree.rs"
required-features = ["updater"]
